collections:
  - blocks
  - roofs
  - billboards

views:
  north_west:
    none:
      content:
        base:
          flip_h: false
        feature:
          color: 0xffffffff
          flip_h: false
      lighting:
        light_side:
          color: 0x10ffffff
          flip_h: true
        light:
          color: 0x10ffffff
  north_east:
    none:
      content:
        base:
          flip_h: false
        feature:
          color: 0xffffffff
          flip_h: true
      lighting:
        light_side:
          color: 0x10ffffff
        light:
          color: 0x10ffffff
  south_west:
    none:
      content:
        base:
          flip_h: false
        feature_back:
          flip_h: true
          color: 0xffffffff
      lighting:
        shade_side:
          color: 0x10ffffff
          flip_h: true
        light:
          color: 0x10ffffff
  south_east:
    none:
      content:
        base:
          flip_h: false
        feature_back:
          color: 0xffffffff
          flip_h: false
      lighting:
        shade_side:
          color: 0x10ffffff
        light:
          color: 0x10ffffff
